language: python
python:
  - "3.6"
  - "3.8"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - py.test  --cov-report term --cov=app/test/
after_success:
  - bash <(curl -s https://codecov.io/bash)
